/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp2;

import java.util.Map;
import javax.swing.table.DefaultTableModel;
import org.jpl7.Query;
import org.jpl7.Term;

/**
 *
 * @author jhonson
 */
public class IngresoManual extends javax.swing.JFrame {

    /**
     * Creates new form IngresoManual
     */
    DefaultTableModel Modelo =new DefaultTableModel();
    MonitoreoInterfaz Cuadro;
    
    public IngresoManual(MonitoreoInterfaz Cuadro) {
        initComponents();
        this.Cuadro=Cuadro;
        this.setResizable(false);
        setDefaultCloseOperation(0);
        setTitle("Ingreso manual de datos");
        jTable2.setModel(Modelo);
    }

    private IngresoManual() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Sismo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel2.setText("Fecha:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setText("Pais:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel4.setText("Cuidad:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel5.setText("Profundidad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel6.setText("Magnitud");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel7.setText("Latitud");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel8.setText("Longitud");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 100, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 100, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 100, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 100, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 100, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 100, -1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 100, -1));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jLabel9.setText("Riesgo:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        jLabel10.setText("Estado:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        jLabel11.setText("Referencia:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 93, -1));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 93, -1));
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 93, -1));
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 90, -1));

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 90, -1));

        jLabel13.setText("Tsunami");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel14.setText("Fecha:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        jLabel15.setText("Pais:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 93, 30));

        jLabel16.setText("Cuidad:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 610, -1, -1));

        jLabel12.setText("Hora:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 100, -1));

        jLabel17.setText("Hora:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));
        getContentPane().add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 93, -1));

        jButton4.setText("Consulta");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        jButton5.setText("Consulta");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 368, 672, 230));

        jLabel18.setText("Zona Riesgo");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        jLabel19.setText("Pais:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        jLabel20.setText("Cuidad:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        jLabel21.setText("Nivel:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));
        getContentPane().add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 90, -1));
        getContentPane().add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 90, -1));
        getContentPane().add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 90, -1));

        jButton6.setText("Consulta");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, -1, -1));

        jLabel22.setText("Nombre:");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));
        getContentPane().add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Comando ="asserta(sismo('"+jTextField1.getText()+"','"+jTextField14.getText()+"','"+jTextField3.getText()+"','"+jTextField2.getText()+"',"
                    +jTextField4.getText()+","+jTextField5.getText()+","+jTextField7.getText()+","+jTextField6.getText()+"))"; 
            Query Ejecucion = new Query(Comando);
            System.out.println(Comando);
            Ejecucion.hasSolution();
            Comando=">>Información encontrada: Sismo en "+jTextField3.getText()+", "+jTextField2.getText()+", con magnitud de "
                    + jTextField5.getText()+ ".\n Se agregó la información en la Base de Conocimiento." +"\n";
            Cuadro.AgregarCuadro(Comando);
            
            Comando="alerta('"+jTextField3.getText()+"','"+jTextField2.getText()+"',"+jTextField5.getText()+",Co,Ni,E,"+"'"+
                    jTextField1.getText()+"',"+jTextField4.getText()+")";
            Ejecucion = new Query(Comando);
            if(Ejecucion.hasSolution()){
                Map<String, Term> Soluciones = Ejecucion.oneSolution();
                String Alerta = ">>NUEVA ALERTA DE TSUNAMI en "+ jTextField3.getText() +", "+  
                jTextField2.getText()+" con nivel "+ Soluciones.get("Co")+", "+Soluciones.get("Ni")+
                " !Alerta "+ Soluciones.get("E")+"¡\n";
                Cuadro.AgregarCuadro(Alerta.replace("'", ""));
                
                Comando ="asserta(tsunami('"+jTextField2+"','"+jTextField14+"','"
                +jTextField3.getText()+"','"+jTextField3.getText()+"',"+Soluciones.get("Ni")+","+
                         Soluciones.get("E")+",'Referencia'"+"))";
                System.out.println(Comando);
                Ejecucion = new Query(Comando);
                Ejecucion.hasSolution();
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String Comando ="asserta(tsunami('"+jTextField8.getText()+"','"+jTextField15.getText()+"','"
                +jTextField10.getText()+"','"+jTextField9.getText()+"','"+jTextField11.getText()+"','"+
                         jTextField12.getText()+"','Referencia'"+"))";
                Query Ejecucion = new Query(Comando);
                Ejecucion.hasSolution();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        String Comando;
        
        if("".equals(jTextField19.getText())){
            Comando="sismo(Nombre,";
        }else{ 
            Comando="sismo('"+jTextField19.getText()+"',";
        }
        if("".equals(jTextField1.getText())){
            Comando+="Fecha,";
        }else{ 
            Comando+="'"+jTextField1.getText()+"',";
        }
        if("".equals(jTextField14.getText())){
            Comando+="Hora,";
        }else{ 
            Comando+="'"+jTextField14.getText()+"',";
        }
        if("".equals(jTextField3.getText())){
            Comando+="Ciudad,";
        }else{ 
            Comando+="'"+jTextField3.getText()+"',";
        }
        if("".equals(jTextField2.getText())){
            Comando+="Pais,";
        }else{ 
            Comando+="'"+jTextField2.getText()+"',";
        } 
        if("".equals(jTextField4.getText())){
            Comando+="Profundidad,";
        }else{ 
            Comando+=jTextField4.getText()+",";
        }
        
        if("".equals(jTextField5.getText())){
            Comando+="Magnitud,";
        }else{ 
            Comando+=jTextField5.getText()+",";
        }
        
        if("".equals(jTextField7.getText())){
            Comando+="Longitud,";
        }else{ 
            Comando+=jTextField7.getText()+",";
        }
        
        if("".equals(jTextField6.getText())){
            Comando+="Latitud)";
        }else{ 
            Comando+=jTextField6.getText()+")";
        }
        
        Query Ejecucion = new Query(Comando);
        Map<String, Term>[] TodaLasSoluciones = Ejecucion.allSolutions();
        if(TodaLasSoluciones !=null){
            Object Columnas [] = TodaLasSoluciones[0].keySet().toArray();
            Modelo = new DefaultTableModel(null,Columnas);
            jTable2.setModel(Modelo);        
            for(Map<String, Term> Solucion : TodaLasSoluciones ){
            Object Fila [] =Solucion.values().toArray();
            Modelo.addRow(Fila);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //su
        String Comando;
        
        if("".equals(jTextField8.getText())){
            Comando="tsunami(Fecha,";
        }else{ 
            Comando="tsunami('"+jTextField8.getText()+"',";
        }
        if("".equals(jTextField15.getText())){
            Comando+="Hora,";
        }else{ 
            Comando+="'"+jTextField15.getText()+"',";
        }
        if("".equals(jTextField9.getText())){
            Comando+="Ciudad,";
        }else{ 
            Comando+="'"+jTextField9.getText()+"',";
        }
        if("".equals(jTextField10.getText())){
            Comando+="Pais,";
        }else{ 
            Comando+="'"+jTextField10.getText()+"',";
        } 
        if("".equals(jTextField11.getText())){
            Comando+="Riesgo,";
        }else{ 
            Comando+="'"+jTextField11.getText()+"',";
        }
        
        if("".equals(jTextField12.getText())){
            Comando+="Estado,";
        }else{ 
            Comando+="'"+jTextField12.getText()+"',";
        }
        
        if("".equals(jTextField13.getText())){
            Comando+="Referencia)";
        }else{ 
            Comando+="'"+jTextField13.getText()+"')";
        }
        System.out.print(Comando);

        Query Ejecucion = new Query(Comando);
        Map<String, Term>[] TodaLasSoluciones = Ejecucion.allSolutions();
        if(TodaLasSoluciones !=null){
            Object Columnas [] = TodaLasSoluciones[0].keySet().toArray();
            Modelo = new DefaultTableModel(null,Columnas);
            jTable2.setModel(Modelo);        
            for(Map<String, Term> Solucion : TodaLasSoluciones ){
            Object Fila [] =Solucion.values().toArray();
            Modelo.addRow(Fila);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        //riesgo('Estados Unidos','Carolina del Norte','Bajo').
        String Comando;
        
        if("".equals(jTextField16.getText())){
            Comando="riesgo(Pais,";
        }else{ 
            Comando="riesgo('"+jTextField16.getText()+"',";
        }
        if("".equals(jTextField17.getText())){
            Comando+="Ciudad,";
        }else{ 
            Comando+="'"+jTextField17.getText()+"',";
        }
        if("".equals(jTextField18.getText())){
            Comando+="Nivel)";
        }else{ 
            Comando+="'"+jTextField18.getText()+"')";
        }
        Query Ejecucion = new Query(Comando);
        Map<String, Term>[] TodaLasSoluciones = Ejecucion.allSolutions();
        if(TodaLasSoluciones !=null){
            Object Columnas [] = TodaLasSoluciones[0].keySet().toArray();
            Modelo = new DefaultTableModel(null,Columnas);
            jTable2.setModel(Modelo);        
            for(Map<String, Term> Solucion : TodaLasSoluciones ){
            Object Fila [] =Solucion.values().toArray();
            Modelo.addRow(Fila);
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoManual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new IngresoManual().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
